FROM quay.io/sampandey001/secktor
RUN git clone
https://github.com/DigitalCen/Centio-Bot /root/DigitalCen
WORKDIR /root/excelottah6/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
